language: node_js
node_js:
  - "12"

addons:
  chrome: stable

env:
  global: CODECOV_TOKEN=$CODECOV_TOKEN

cache:
  directories:
    - ./node_modules

before_script:
  - npm install

jobs:
  include:
    - stage: Test coverage
      script:
        - npm run test
      after_script:
        - bash <(curl -s https://codecov.io/bash)
